### ISSUE TITLE
Limit download sizes (or document how to control them)

### ISSUE THREAD

**Issue by manics** [ome/omero-web#118]
Recently the UoD production server has temporarily run out of space, presumably due to large temporary files (several GB).

Nginx error log:

`2020/01/29 15:01:10 [error] 1623#1623: *433114 upstream timed out (110: Connection timed out) while reading response header from upstream, client: X.X.X.X, server: X, request: "GET /webgateway/archived_files/download/?image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&zipname=OriginalFileDownload.zip HTTP/1.0", upstream: " [http://127.0.0.1:4080/webgateway/archived_files/download/?image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&amp:image=X&zipname=OriginalFileDownload.zip] , host: "nightshade.openmicroscopy.org", referrer: " [https://nightshade.openmicroscopy.org/webclient/download_placeholder/?ids=image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X❘image-X)]`

I checked one of the images, the associated file is 360 MB.

**Comment by manics** [comment]
Maybe this should be a cross-repo issue? `/webgateway/archived_files` is a web method, but a similar issue would arise with e.g. the batch-download script if someone decided to download several GB or TB of data.

**Comment by joshmoore** [comment]
This was just hit again, temporarily filling up a partition that had ~2.5 GB free.

**Comment by manics** [comment]
Timeout today on Nightshade: `GET /webgateway/archived_files/download/?<long list of image=...>`

**Comment by manics** [comment]
Again today, on nightshade.

**Comment by manics** [comment]
Example of the large temporary files that are used by Nginx when buffering a large response:
```
$ head -n1 lsof-20200728-1040; grep /var/cache/nginx lsof-20200728-1040
COMMAND     PID   TID             USER   FD      TYPE             DEVICE    SIZE/OFF       NODE NAME
nginx      4523                  nginx    3u      REG              253,0   306241536   18613995 /var/cache/nginx/proxy_temp/0/60/0000000600 (deleted)
nginx      4523                  nginx   20u      REG              253,0   341581824    8600422 /var/cache/nginx/proxy_temp/6/59/0000000596 (deleted)
nginx      4523                  nginx   27u      REG              253,0   424144896       5447 /var/cache/nginx/proxy_temp/8/59/0000000598 (deleted)
nginx      4523                  nginx   34u      REG              253,0   601034752   25539840 /var/cache/nginx/proxy_temp/2/60/0000000602 (deleted)
nginx      4523                  nginx   39u      REG              253,0   388808704    8602007 /var/cache/nginx/proxy_temp/4/60/0000000604 (deleted)
```
