### ISSUE TITLE
How to configure tests for OMERO.web apps using IWebTest

### ISSUE THREAD

**Issue by fireofearth** [ome/omero-web#122]
I'm creating an [app](https://docs.openmicroscopy.org/omero/5.6.0/developers/Web/CreateApp.html) for OMERO.web (5.6.0) and I wish to test URLs that return JSON or html.

My URLs require the `login_required` decorator from the `omeroweb.webclient.decorators` module, and is run with `DJANGO_SETTINGS_MODULE=omeroweb.settings  pytest tests/test_views.py`. I'm getting the `omero.ClientError` "No host specified. Use omero.client(HOSTNAME), ICE_CONFIG, or similar." How do I configure tests for apps?

```
import pytest
import omero

from django.core.urlresolvers import reverse

from omeroweb.testlib import IWebTest
from omeroweb.testlib import get, post, get_json
from aimviewer.config import (TEST_DATASET, TEST_IMAGE_1)
import aimviewer.views as views


class TestView(IWebTest):

    def test_get_image_nav(self):
        new_user = self.new_user()
        omeName = new_user.omeName.val
        django_client = self.new_django_client(omeName, omeName)
        request_url = reverse(views.get_image_nav,
                kwargs={'dataset_id': TEST_DATASET,
                        'image_id': TEST_IMAGE_1})
        rsp = get_json(django_client, request_url)
        print(rsp)
```

**Comment by fireofearth** [comment]
This is based on <https://forum.image.sc/t/how-to-configure-tests-for-omero-web-apps-using-iwebtest-in-omeroweb-testlib/33755> by posting here as it may be more relevant.

**Comment by joshmoore** [comment]
Hi @fireofearth 

The integration tests for OMERO.web live in the ome/openmicroscopy repository. There you can find an example ice.config file:

https://github.com/ome/openmicroscopy/blob/develop/etc/ice.config

Especially of importance is the `omero.rootpass` with the admin password for your *test* system. My own looks like this:

```
$ cat /opt/cfg
omero.host=localhost
omero.port=4064
omero.rootpass=omero
omero.user=root
omero.pass=omero
omero.web.debug=True
```
(etc.)

I set it via:

```
export ICE_CONFIG=/opt/cfg
```

Hope that helps.
~Josh

**Comment by fireofearth** [comment]
Thanks. This doesn't work off the bat, but I'll tinker around with the config file and get back to you if I have any more questions.

**Comment by fireofearth** [comment]
Hi there, just had the time to look at this again, and and I'm still confused as how testing works. Note my app builds up from the template app <https://github.com/ome/omero-web-apps-examples/tree/master/minimal-webapp>.

The change I made is now I run pytest using the command `export DJANGO_SETTINGS_MODULE=omeroweb.settings; export ICE_CONFIG='/path/to/ice.config'; pytest tests/test_views.py`. I'm getting a bunch of these errors

```
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Due to requests for `/webclient/login` made during initialization.

**Comment by fireofearth** [comment]
Thanks, to followup, this helps a lot!
