### ISSUE TITLE
JSON API error with childCount if no Objects

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#146]
e.g. /api/v0/m/screens/?childCount=true
fails if there are no Screens 
```
ome.conditions.ApiUsageException: unexpected end of subtree
```
Reported at https://forum.image.sc/t/omero-gallery-lock-up-issue-and-different-viewer-option/34259

**Comment by joshmoore** [comment]
Again in QA 29645

**Comment by will-moore** [comment]
Fixed in https://github.com/ome/omero-web/pull/249
