### ISSUE TITLE
Bug: Edit current group name

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#163]
See https://www.openmicroscopy.org/qa2/qa/feedback/29225/

```
serverStackTrace = ome.conditions.ValidationException: cannot rename the current group context '***'
at ome.logic.AdminImpl.updateGroup(AdminImpl.java:619)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

If an Admin renames the group they are currently logged in to, you get a ValidationException.

There is a `can_modify_group` flag, which could be set to False if you're editing your current group. 
https://github.com/ome/omero-web/blob/e5b30a74bab82dffe26a3df4cf6f57a104e9e723/omeroweb/webadmin/views.py#L715

But that might not be the nicest usability - No info to tell you why you can't edit group. Also prevents changing permissions on the group, which I don't *think* should be disabled. Don't know about editing description.
Might need another flag 'current_group' to disable those fields instead of hiding them, and also showing tooltip.

**Comment by will-moore** [comment]
Reported again at https://www.openmicroscopy.org/qa2/qa/feedback/29710/

**Comment by will-moore** [comment]
Reported again at https://www.openmicroscopy.org/qa2/qa/feedback/29778/

**Comment by will-moore** [comment]
Reported again 5.9.2 at https://www.openmicroscopy.org/qa2/qa/feedback/30416/

**Comment by will-moore** [comment]
Again https://www.openmicroscopy.org/qa2/qa/feedback/31264/

**Comment by will-moore** [comment]
Again at https://www.openmicroscopy.org/qa2/qa/feedback/32927/

**Comment by jburel** [comment]
this has been an issue now for a while.
We should look into fix that bug.
