### ISSUE TITLE
Shares deprecated and broken in UI

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#179]
See https://github.com/ome/omero-iviewer/issues/324

Need to highlight in the Share dialog itself that they are deprecated and may not work everywhere.

As mentioned on the issue below, OMERO doesn't let you list usernames for users who are not in any of your non-private groups. So this really breaks shares.

**Comment by will-moore** [comment]
Steps / options for removing shares...

 - Remove the "Create Share" button like this:
 
Before:

![Screenshot 2021-02-25 at 13 35 58](https://user-images.githubusercontent.com/900055/109160982-6df7db00-776e-11eb-84a0-dcdda57a076c.png)

After:

![Screenshot 2021-02-25 at 13 35 07](https://user-images.githubusercontent.com/900055/109160900-515ba300-776e-11eb-9a44-4cb5f3f78059.png)

 - Alternative is to leave it, but it's always greyed-out with a tooltip that says "Shares not supported. Use 'duplicate instead'" or it could popup the Share dialog, which says the same, with more details?
 - Remove endpoint `webclient/action/add/share/` GET and POST endpoint (used by that dialog) and python `createShare()` code.
 - It's really the *creation* of Shares that is now broken (because you can't see any users, except those in your read-* groups). But if you have any existing shares, these may still be working. So do we leave the "Shares" tab and all other share support, such as `shareId` in `webclient/[shareId]/imgData/[imageId]/` and `webclient/[shareId]/render_image/[imageId]/`.

**Comment by will-moore** [comment]
cc @pwalczysko @jburel Thoughts on whether to remove the 'Create Share' button, or replace the "Share" dialog with a "Use duplicate instead" message? Like "[Please do not press this button again](https://www.goodreads.com/quotes/44928-arthur-dent-what-happens-if-i-press-this-button-ford)".

**Comment by jburel** [comment]
Removing does not seem to be a good approach. It will be better to suggest the alternative "User CLI duplicate"

**Comment by will-moore** [comment]
When suggesting the `duplicate` alternative, we'll need to mention the limitations (probably need to mention these in https://github.com/ome/omero-guide-introduction/pull/19 too):

 - Duplicate is only available via the CLI
 - You need to already be in a non-private group with the user you wish to share with
 - You will also be sharing the data with all the other members of that group

Should I also provide a link to https://omero-guides.readthedocs.io/projects/introduction/en/latest/data-management.html?highlight=duplicate#command-line-duplicating-objects ? Is that URL stable enough?
When trying to google "OMERO duplicate", I didn't see that page on the first page of results. I got https://pypi.org/project/omero-cli-duplicate/ (which doesn't say how to use it, or even what it does) and https://omero-guides.readthedocs.io/_/downloads/introduction/en/latest/pdf/ which is useable, but not as nice as finding the web page.
We probably should link to the guides from the `omero-cli-dupliate` README.

**Comment by pwalczysko** [comment]
I would suggest:

``Sorry, this feature is no longer available. You can see if you can use Duplicate feature (link?) as a replacement.``
Yes, the link should probably go to the guide, and we should explain all the particularities there. Imho, majority of potential Share users will never be satisfied with Duplicate as a replacement, and for those, reading the Duplicate doc through would not bring much - best to prepare them for this upfront, but not to clutter the OMERO.web with complex explanations either.

**Comment by will-moore** [comment]
PR opened at https://github.com/ome/omero-web/pull/265
I tried to give a bit more info up-front. To avoid users potentially wasting time looking at `omero-cli-duplicate` if it wasn't going to work for them.

**Comment by joshmoore** [comment]
Reviewed:
 * https://github.com/ome/omero-web/pull/265
 * https://github.com/ome/www.openmicroscopy.org/pull/447
 * https://github.com/ome/omero-guide-introduction/pull/19

Nicely done!
