### ISSUE TITLE
Bottom of left-hard tree can be obsured by mouse-over link status bar

### ISSUE THREAD

**Issue by manics** [ome/omero-web#234]
If you have a long list of containers in the tree it reaches all the way to the bottom of the browser view.
If you mouseover a container higher in the tree in Firefox the link target is shown in the bottom left of the browser. This may obscure the last study in the list.

In the following screenshot I've scrolled to the bottom of the LH tree, my mouse is hovering over `idr0082-pennycuick-lesions/experimentA` and the last study `idr0094-ellinger-sarscov2/screenB` is obscured.

<img width="369" alt="Screen Shot 2020-10-06 at 10 24 51" src="https://user-images.githubusercontent.com/1644105/95183887-83b83400-07be-11eb-8ad6-56cddc4f6724.png">

In order to get to the last study it's natural for the mouse to move over the items higher in the tree therefore displaying the link status, so this is a usability issue.

**Comment by pwalczysko** [comment]
thanks @manics , I hit this problem very commonly in IDR too

**Comment by manics** [comment]
Possible fix: Add `padding-bottom: 2em;` to the `.jstree-children` CSS class
