### ISSUE TITLE
CHANGELOG.md wrong links to 2021-SV1 and 2021-SV2

### ISSUE THREAD

**Issue by stiftovich** [ome/omero-web#279]
The links that should direct you to the security advisories 2021-SV1 and 2021-SV2 are wrong.
Use https://www.openmicroscopy.org/security/advisories/2021-SV1/ and https://www.openmicroscopy.org/security/advisories/2021-SV2/ instead.

**Comment by jburel** [comment]
Thanks. We had redirect in-place and opted to remove them. We forgot to update them
This is now fixed

**Comment by jburel** [comment]
https://github.com/ome/omero-web/commit/e2cec7c1f56a54dea2d9b4c61ab4a135bee31ac1
