### ISSUE TITLE
webclient/imgData missing LUT

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#287]
When working on the generation of figure, i noticed that the json returned using ``baseURL/webclient/imgData/ID``
does not have the notion of LUT
cc @will-moore

**Comment by sbesson** [comment]
@jburel isn't `lut` an optional field per channel in the JSON response of the `imgData` endpoint? See https://idr.openmicroscopy.org/webclient/imgData/5514379/ for instance

**Comment by jburel** [comment]
you are correct. The image I am looking at does not have one. closing
