### ISSUE TITLE
[Security] Outdated Django in use

### ISSUE THREAD

**Issue by tuxmaster5000** [ome/omero-web#353]
In the setup.py I see, that it will depends on Django 1.11.  But this is EOL since 2020.
See https://www.djangoproject.com/download/#supported-versions for more.
How will it be possible to let it run in an secure manner, when it will use outdated 3rd party modules?

**Comment by sbesson** [comment]
Thanks @tuxmaster5000 for raising this important question. As detailed in our [OME security policy](https://github.com/ome/omero-web/security/policy), our security mailing list should be the primary mean of communication for all discussions associated with security issue. Thus I will close this issue but feel free to reach out using the list if you have some specific concerns.

Summarizing briefly the current state, it is correct that `omero-web` currently depends on `Django 1.11`. Some background investigation has been started on upgrading this dependency, see for instance [#200](https://github.com/ome/omero-web/pull/200). We will work towards a more comprehensive report of the state and the implication of this upgrade and the roadmap shortly.

**Comment by sbesson** [comment]
Following-up, https://www.openmicroscopy.org/2022/02/18/omeroweb-django-upgrade.html should summarize our current assessment of the situation including the current open roadmap for upgrading to Django 3.2
