### ISSUE TITLE
Hidden download button in "Activities"

### ISSUE THREAD

**Issue by Tom-TBT** [ome/omero-web#377]
Hello,
Following "Run script"->"export scripts"-> "Batch Image Export..."
the "Download File" button in "Activities" gets hidden when the exported Image_name or Folder_name is too long

![notFitting](https://user-images.githubusercontent.com/10853316/171595423-fbbc5c42-33f2-4773-8a89-c49b939fd9f9.png)

After some testing, this happens only when there is no space in the name, adding a space let it print the name on several lines:
![Fitting space](https://user-images.githubusercontent.com/10853316/171595768-f9b4afac-02c9-4a40-a4dd-980ca13e69d3.png)

Additionally, this affects previous notifications (but is reset if we clear the list):
![notFitting_anymore](https://user-images.githubusercontent.com/10853316/171595958-9a382660-53bf-4cbf-96b4-a7bbba970089.png)

A quick workaround is to select first an image with a short name (that's the one that will be printed in the "Activities").

Looking around the possibilities to fix that, a quick but dirty solution is to trim the message displayed when too long. That could be done in the concerned script [(Batch_Image_Export.py#L615).](https://github.com/ome/omero-scripts/blob/a90f59802f6752ad74badec5c0c1d6b0c9c43b15/omero/export_scripts/Batch_Image_Export.py#L615) 

The second and better solution, in my opinion, is to handle it in omero-web, as other messages could be concerned. But this is the point where I'm getting lost in the code...

Best,
Tom

**Comment by will-moore** [comment]
Thanks for reporting this - I'll look into it...

**Comment by will-moore** [comment]
The fix for this at https://github.com/ome/omero-web/pull/378 has now been released in omero-web 5.15.0.
