### ISSUE TITLE
Server is not used by default when authenticating via GET param

### ISSUE THREAD

**Issue by hpawe01** [ome/omero-web#379]
Hello,

I want to login to the webclient using the `bsession` query param:
https://github.com/ome/omero-web/blob/d4f857d2f021d032734ac314c651454172a75369/omeroweb/decorators.py#L424-L440

This is not working because of the lines before:
https://github.com/ome/omero-web/blob/d4f857d2f021d032734ac314c651454172a75369/omeroweb/decorators.py#L409-L420

I need to explicitly provide `server=1` as query param to make it work, although @will-moore states [here](https://github.com/ome/omero-iviewer/issues/197#issuecomment-379192508) that we shouldn't need to set it for the default configuration. This is only true, if we already have a session - then the `server_id` is retrieved from the `connector` which comes from the `session`: https://github.com/ome/omero-web/blob/d4f857d2f021d032734ac314c651454172a75369/omeroweb/decorators.py#L406

As I said, it is working when I provide `server=1` but the problem is, that this same query param is used for something else in [OMERO.iviewer](https://github.com/ome/omero-iviewer/blob/f98323a4bf24e3474537bd79195283e909dac78c/src/app/context.js#L431-L445). So when I want to open an image in OMERO.iviewer with "auto-login" via `bsession`, I could
- add `server=1`, then the login works but the the viewer crashes
- omit `server=1`, then the login will not work but the viewer would

I think we should use the default `server_id` when the param `server` is missing but I don't really know how to get it. Otherwise I would create a pull request.

**Comment by will-moore** [comment]
Hi, apologies for delayed response.
I think the best solution here is to update iviewer to use a different parameter instead of `server`, since this is really a developer option and changing this won't break any use-case.
I've opened a PR to rename it to `host` at https://github.com/ome/omero-iviewer/pull/414

**Comment by will-moore** [comment]
"don't use the server by default" - you mean that we only check `?server=1` if `connector` is None?
You would prefer that we always check the GET request for `server` first?

**Comment by will-moore** [comment]
The iviewer fix at https://github.com/ome/omero-iviewer/pull/414 is released. Omero-web fix will be in next release of that too...

**Comment by will-moore** [comment]
The fix in https://github.com/ome/omero-web/pull/386 has now been released in omero-web.
