### ISSUE TITLE
Add comment on large number of objects

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#401]
* Select a large number of objects e.g. 500 Possible with https://github.com/ome/omero-web/pull/225
* Go to the Comments harmonica
* Enter text and click ``Add comment``
* Comment does not get saved

**Comment by pwalczysko** [comment]
For me, the comment does get saved after a while. This might be dependent on internet speed, but there is a definite lag with no explanation even on the institutional internet I am on now.
