### ISSUE TITLE
Large Selection of images: Show parent Projects and Datasets

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#405]
* Select a large number of objects e.g. 500 Possible with https://github.com/ome/omero-web/pull/225
* Click on the button to ``Show parent Projects & Datasets``
* Nothing happens
<img width="1512" alt="Screenshot 2022-09-15 at 10 50 25" src="https://user-images.githubusercontent.com/1022396/190373647-ccdfb773-d629-44c3-a899-32305e442670.png">

**Comment by pwalczysko** [comment]
I can confirm this.
