### ISSUE TITLE
Large selection: Show KVP

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#407]
* Select a large number of objects e.g. 500 Possible with https://github.com/ome/omero-web/pull/225
*  Large number of KVP
* Click on arrow to expand and load
* ``Loading...`` message is displayed once but nothing gets displayed
* No more message after expanding a second time, still nothing loaded

**Comment by pwalczysko** [comment]
This works for me, maybe I do not understand the description. After I click on the harmonica Key-Value pairs (1000), the harmonica expands as expected, after a short wait with a message "Loading...". After that, I can see the KVPs. I can also collapse and expand again, this time without a wait.
Might be dependent on internet speed ? (this is done from UoD network)
