### ISSUE TITLE
Dependabot alert - DoS vulnerability in Django < 3.2.17

### ISSUE THREAD

**Issue by knabar** [ome/omero-web#447]
See https://github.com/ome/omero-web/security/dependabot/2

In Django 3.2 before 3.2.17, 4.0 before 4.0.9, and 4.1 before 4.1.6, the parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if the raw value of Accept-Language headers is very large.

**Comment by sbesson** [comment]
Should we update https://github.com/ome/omero-web/blob/6e25b39df40dbe6e84994430a022be369898c3a3/setup.py#L57 to require 3.2.17 minimum? Or maybe even [3.2.18](https://docs.djangoproject.com/en/4.1/releases/3.2.18/) which has been released since and addresses another vulnerability
