### ISSUE TITLE
Issue with script message size in the activities panel

### ISSUE THREAD

**Issue by TorecLuik** [ome/omero-web#488]
Hey OME,

The script message size CSS (of the `activities panel`) is not working well with the currently given sizes.
So sometimes you cannot get to the buttons of the script output anymore, if the message is too big.

I.e. 

1. the `#activities_panel` has a `width: 400px`
2. the `.script_description` has a `width: 200px;`  but that doesn't seem to matter.
3. the `#activities_panel .message ` has no width. _If we set that to e.g. `width: 300px`, we can see our buttons again._

I am using `omero-web-standalone` from [Docker v5](https://hub.docker.com/layers/openmicroscopy/omero-web-standalone/5/images/sha256-87ba277ed1496a965e57a536edc67f30af623edc1f0e129e746f891dd5c1b2a6?context=explore) with Chrome.

![activities_panel_no_width](https://github.com/ome/omero-web/assets/68958516/b9b943ff-91f0-4147-affd-56b317ed37ff)
![activities_panel_width](https://github.com/ome/omero-web/assets/68958516/d3a42720-3668-4d1e-a2e2-ea6c3af04793)

**Comment by will-moore** [comment]
Thanks for the feedback.
I think this issue was fixed in https://github.com/ome/omero-web/pull/378
which was released in https://github.com/ome/omero-web/blob/master/CHANGELOG.md#5150-august-2022.
Can you check what version of `omero-web` you have (on the webclient login page)?

**Comment by TorecLuik** [comment]
Ok, thanks for the info, then we can probably close this. 

This is version "OMERO.web 5.13.0."
From 'openmicroscopy/omero-web-standalone:5' 

I should probably use more specific versions in the dockerfiles, so I know when to rebuild/upgrade =)
