### ISSUE TITLE
Add attachment dialog not loading

### ISSUE THREAD

**Issue by dominikl** [ome/omero-web#499]
See https://forum.image.sc/t/unable-to-add-attachment-using-omero-web/84146/ .
The number of available attachments for the logged in user is probably too long. Pagination required?

**Comment by will-moore** [comment]
To try and reproduce locally, need lots of FileAnnotations...
Pick an existing OriginalFile and create lots...

```
$ omero login

$ for i in {1..10000}; do omero obj new FileAnnotation file=OriginalFile:3070; done

Using session for will@localhost:4064. Idle timeout: 10 min. Current group: Swedlow Lab
FileAnnotation:2530
...
```

**Comment by will-moore** [comment]
I don't know how many `FileAnnotations` are needed to cause the exception reported above, but I think that the user in that case is not trying to pick from E.g. 10000 existing FileAnnotations, but is just trying to upload a NEW File.

It may be that if you've got enough FileAnnotations to trigger the `Ice::MemoryLimitException` then the web UI might also do a bad job (or fail) to display them so you can actually pick one. It would be a shame if this broke the "Upload File" functionality. So we should probably pick a number of FileAnnotations that we know works OK, and if the user has more than that, we say "additional files not loaded".

**Comment by joshmoore** [comment]
:+1: with incremental improvements being:
 - stating the number of additional files (fairly straight-forward)
 - allowing paging through the additional files (probably quite a bit of work)

**Comment by chris-allan** [comment]
@knabar / @will-moore: Also close with #517 and the merge and release of #519 in 5.24.0?

**Comment by will-moore** [comment]
Yep - issue is fixed now, thx 👍
