### ISSUE TITLE
An error occurred where omero config append

### ISSUE THREAD

**Issue by busing** [ome/omero-web#525]
I'm sorry, I deployed OMERO according to the document, but an error occurred at this step. The error is as follows. I am using Windows.

`
omero config append omero.web.server_list '["192.168.31.54", 4064, "demo"]

ERROR :
usage: C:\Users\taiyu\.conda\envs\omeroweb\Scripts\omero config append
       [-h] [--report] [--set] KEY VALUE
C:\Users\taiyu\.conda\envs\omeroweb\Scripts\omero config append: error: unrecognized arguments: 4064, demo]

`

**Comment by will-moore** [comment]
It looks like you're missing a `'` at the end of what you've pasted above?

There should be a closing single quote after the last square bracket:
```
omero config append omero.web.server_list '["192.168.31.54", 4064, "demo"]'
```

**Comment by busing** [comment]
Sorry , I made a mistake in writing.

Still the same mistake
![image](https://github.com/ome/omero-web/assets/9995678/fc7c0168-e588-4e2d-868c-64d84c876296)

**Comment by joshmoore** [comment]
Hi @busing. Quote characters work quite differently on Windows (and we're not experts). You can examples under, e.g., https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter

I think you will need something like:

```
omero config append omero.web.server_list "[\"192.168.31.54\", 4064, \"demo\"]"
```

**Comment by busing** [comment]
It has worked, thank you~~
