### ISSUE TITLE
JavaScript error when right-clicking while multiple datasets are selected

### ISSUE THREAD

**Issue by knabar** [ome/omero-web#559]
Selecting multiple datasets (using Shift key) and then right-clicking causes a JavaScript error:

<img width="937" alt="Screenshot 2024-05-31 at 14 04 49" src="https://github.com/ome/omero-web/assets/197099/54964387-10d0-41a5-87b2-0188cd328bd1">

All "Open With..." entries are disabled.

**Comment by will-moore** [comment]
Unfortunately the stack trace doesn't give much, but I'm wondering if this could be the `isEnabled()` function provided by one of the Open With plugins?
Called at https://github.com/ome/omero-web/blob/9c94fd493eb94588de8432247e084be57d7ea928/omeroweb/webclient/static/webclient/javascript/ome.tree.js#L1126
We probably need to wrap that in a try/except (with console logging etc) so it doesn't break the whole menu if it fails - and we can see if/which particular plugin is causing the issue.

**Comment by knabar** [comment]
@will-moore Good point, I reset the `omero.web.open_with` setting so that only "ImageViewer" shows up, and it no longer causes a JavaScript error. 

try/except sounds like a good solution, especially since it could print the name of the offending plugin.

**Comment by knabar** [comment]
On further investigation, the error actually does not occur in the `isEnabled` or `action` methods; it is contained completely in a plugin.

Closing this issue here.
