### ISSUE TITLE
Infinite loop when downloading tables with <10 rows.

### ISSUE THREAD

**Issue by MicheleBortol** [ome/omero-web#593]
**Bug**

Trying to download an omero table with < 10 rows with the "Whole Table" download button (top right) causes an infinite loop and a wrong and always increasing download size (here `3MB`  for a real total size of ~ `79.59 KB` ) to be displayed:
![image](https://github.com/user-attachments/assets/0ae14722-4d4e-4dc8-af00-7ac902b7abf4)

The "Show current page as: CSV | JSON" links seem be work correctly.

**To Reproduce**

Open any table with less than 10 rows in omero web and click the "Whole Table" download button (top right).
![image](https://github.com/user-attachments/assets/aca06786-0c36-451d-9d53-78ccd3983c79)

Quick examples at:
- https://idr.openmicroscopy.org/webclient/omero_table/39275220/ (1 row)
- https://idr.openmicroscopy.org/webclient/omero_table/34961908/ (5 rows)

With  rows >= 10 everything works:
- https://idr.openmicroscopy.org/webclient/omero_table/15349581/ (10 rows)
- https://idr.openmicroscopy.org/webclient/omero_table/43413223/ (27 rows)

**Cause and fix?**

In [omero_table.html](https://github.com/ome/omero-web/blob/master/omeroweb/webclient/templates/webclient/annotations/omero_table.html) in the `download_csv` function in this [line](
https://github.com/ome/omero-web/blob/213bb61adc23aed4a750f2a83dc94b7efdb22cee/omeroweb/webclient/templates/webclient/annotations/omero_table.html#L219C36-L219C57) the `batchSize`  evaluates to `0` for  values of `rowCount` < 10.
Then, when `count` is incremented [here](https://github.com/ome/omero-web/blob/213bb61adc23aed4a750f2a83dc94b7efdb22cee/omeroweb/webclient/templates/webclient/annotations/omero_table.html#L255), since `batchSize`  is  `0` the `count` remains `0` causing the infinite loop.

I think this could be solved by forcing the `batchSize` to be at least `1` e.g. with:
`const batchSize = Math.min(Math.max(parseInt(rowCount/10), 1), MAX_BATCH_ROWS);`
If it is OK, I could open a PR with this change.

**Comment by knabar** [comment]
Thank you for investigating this, @MicheleBortol! I will work on a fix for the upcoming release.
