### ISSUE TITLE
Bug: web closes used table

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#6]
see:
 * https://forum.image.sc/t/server-error-after-populating-metadata-for-images-using-web-script/27844
 * https://www.openmicroscopy.org/qa2/qa/feedback/27793
 * https://github.com/openmicroscopy/openmicroscopy/pull/6070

Multiple (browser?) threads accessing the same table proxy can lead to a `NoneType` exception on `table.getHeader()` if one thread calls `close()` while other threads are still active.

Options seem to be:
 - client: use multiple services
 - client: only close when complete
 - client: re-open on the fly
 - server: re-open on the fly
 - (longer-term): use a stateless interface

**Comment by joshmoore** [comment]
Sorry, @will-moore. I missed this go by. Does the above mean that https://github.com/ome/omero-web/issues/6#issuecomment-522952150 isn't a possible solution?

**Comment by will-moore** [comment]
No, I think the JavaScript calls "in series" will fix this issue.
But longer term, it seems that a "lower level" fix would be more robust.
Also it would be nice not to try 6 different ways to get the data since if we don't get it till the 6th try, then it's going to feel a bit slower than you'd like.

**Comment by will-moore** [comment]
https://github.com/ome/omero-web/pull/25 for a potential fix/workaround.

**Comment by will-moore** [comment]
Reported again at https://www.openmicroscopy.org/qa2/qa/feedback/28005/

**Comment by will-moore** [comment]
This seems to be fixed by #25. Closing...
