### ISSUE TITLE
webadmin disk space usage is inconsistent

### ISSUE THREAD

**Issue by manics** [ome/omero-web#68]
Overall:
<img width="739" alt="Screen Shot 2019-11-13 at 10 48 53" src="https://user-images.githubusercontent.com/1644105/68757318-a91add00-0603-11ea-861e-6a1d7f28e75d.png">
Drive space usage: 95%, Total 1.57 TB, Free 65.39GB

`/OMERO` is on the root partition
```
$ df -h /OMERO
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-root  140G   74G   66G  54% /
```
The space usage numbers don't match. The partition isn't 95% full, nor does it have 1.57 TB data (presumably this includes in-place? should be shown separately)

Click on `trainer-1`
<img width="735" alt="Screen Shot 2019-11-13 at 10 49 52" src="https://user-images.githubusercontent.com/1644105/68757616-20e90780-0604-11ea-9c26-7023940b8371.png">
Drive space usage: 85%, User 426.81 GB, Free 65.39GB

Go back and click on one of the users with 1% usage
<img width="774" alt="Screen Shot 2019-11-13 at 10 50 39" src="https://user-images.githubusercontent.com/1644105/68757759-6574a300-0604-11ea-9808-4a248b4caecc.png">
Drive space usage: 17%, User 14.00 GB, Free 65.39GB
Proportionally these numbers don't match up with the total or trainer-1 figures

**Comment by joshmoore** [comment]
Is this a regression?
